### PR TITLE
Rich0003/font1670 100 15 2 update protobuf to 3 21 12

### PR DESCRIPTION
**Pull request by rshepherd549**
Issue: https://devtopia.esri.com/runtime/fontana/issues/1670
vtest: https://runtime-rtc.esri.com/view/Release/job/100.15.0/view/vTest/job/vtest/job/3rdparty-interface/60/downstreambuildview/

### CODE REVIEW

**Comment by rshepherd549** [comment]
vtest: https://runtime-rtc.esri.com/view/Release/job/100.15.0/view/vTest/job/vtest/job/3rdparty-interface/61/downstreambuildview/

All looks good, except Mac? cc @chri7325 . This looks an unrelated, more widespread problem
```
error: Esri/zlib.git: git clone --depth 1 git@github.com:Esri/zlib.git -b release/100.15.0 /Users/apptest/jenkins/workspace/100.15.0/vtest/3rdparty-macos/3rdparty/zlib
Cloning into '/Users/apptest/jenkins/workspace/100.15.0/vtest/3rdparty-macos/3rdparty/zlib'...
kex_exchange_identification: read: Connection reset by peer
Connection reset by 192.30.255.112 port 22
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by chri7325** [comment]
@rshepherd549 the correct branch is actually release/100.15.0. I changed the base but it seems there's conflicts now. As for the error you got on vTest, that happens when GitHub throttles cloning operations when we hit the limit. The better thing to do on vTest is to remove the `runtimecore` from the default branch and just  use your custom branches. This will only build protobuf and protobuf_generated instead of trying to clone and build all of 3rdparty.

**Review by chri7325 — APPROVED** [review]

**Comment by chri7325** [comment]
> seems there's conflicts now

Scratch that, this was just due to missing a reviewer.

**Comment by rshepherd549** [comment]
vtest (protobuf only): https://runtime-rtc.esri.com/view/Release/job/100.15.0/view/vTest/job/vtest/job/3rdparty-interface/62/downstreambuildview/

**Pull request merged**
