### PR TITLE
Rich0003/update protobuf for 200 1 to 3 21 12

### PR DESCRIPTION
**Pull request by rshepherd549**
Issue: https://devtopia.esri.com/runtime/fontana/issues/1633
vtest: https://runtime-rtc.esri.com/view/vTest/job/vtest/job/3rdparty-interface/301/downstreambuildview/

### CODE REVIEW

**Comment by rshepherd549** [comment]
(branch name `rich0003/update_protobuf_for_200_1_to_3_21_12`) https://runtime-rtc.esri.com/view/vTest/job/vtest/job/3rdparty-interface/303/downstreambuildview/

**Comment by rshepherd549** [comment]
(both branch names `rich0003/update_protobuf_for_200_1_to_3_21_12`) https://runtime-rtc.esri.com/view/vTest/job/vtest/job/3rdparty-interface/305/downstreambuildview/

**Comment by rshepherd549** [comment]
https://runtime-rtc.esri.com/view/vTest/job/vtest/job/3rdparty-interface/307/downstreambuildview/

**Review by alexjpayne — APPROVED** [review]
LGTM

**Review by chri7325 — APPROVED** [review]
Looks good, friendly reminder to use a normal merge and not a squash

**Pull request merged**
